/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0a1f18",
        "surface-variant": "#dce5df",
        "surface": "#f3fbf6",
        "surface-dim": "#d3dcd7",
        "primary-fixed-dim": "#b4ccc1",
        "surface-tint": "#4d635a",
        "surface-bright": "#f3fbf6",
        "surface-container": "#e7f0eb",
        "error": "#ba1a1a",
        "surface-container-highest": "#dce5df",
        "on-primary-container": "#768d83",
        "inverse-primary": "#b4ccc1",
        "tertiary-fixed-dim": "#f0bf5c",
        "secondary": "#ad3031",
        "on-tertiary-fixed": "#261900",
        "secondary-fixed-dim": "#ffb3ae",
        "secondary-container": "#ff6b68",
        "on-secondary-fixed-variant": "#8c161d",
        "secondary-fixed": "#ffdad7",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdea4",
        "tertiary": "#0f0800",
        "on-tertiary": "#ffffff",
        "primary-container": "#0f241d",
        "inverse-surface": "#2a322f",
        "on-surface-variant": "#424845",
        "on-background": "#151d1a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf3ee",
        "outline-variant": "#c2c8c4",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#5d4200",
        "primary": "#000b07",
        "on-tertiary-container": "#ab8123",
        "tertiary-container": "#2c1e00",
        "on-primary-fixed-variant": "#364b43",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf6f0",
        "on-primary": "#ffffff",
        "outline": "#727875",
        "background": "#f3fbf6",
        "on-secondary-container": "#6d000d",
        "primary-fixed": "#d0e8dd",
        "on-surface": "#151d1a",
        "error-container": "#ffdad6",
        "surface-container-high": "#e2eae5",
        "on-secondary-fixed": "#410005"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "margin": "2rem",
        "gutter-mobile": "0.75rem",
        "space-xl": "2.5rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Newsreader", "serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "sans": ["Inter", "sans-serif"],
        "serif": ["Newsreader", "serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["9px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "500" }],
        "headline-xl": ["38px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-lg": ["13px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
