/**
 * Curated RAG Evaluation Dataset for Cricket Laws & Playing Conditions
 */
export const EVALUATION_DATASET = [
  {
    id: 'EVAL-01',
    category: 'direct_law',
    query: 'What happens if the ball hits the protective helmet placed behind the wicketkeeper?',
    expectedLaw: 28,
    expectedClause: '28.3.2',
    expectedOrg: 'MCC',
    expectedKeywords: ['dead', '5 penalty runs'],
    applicableFormat: 'ALL',
  },
  {
    id: 'EVAL-02',
    category: 'exact_law_number',
    query: 'Explain MCC Law 31 Timed Out',
    expectedLaw: 31,
    expectedClause: '31.1',
    expectedOrg: 'MCC',
    expectedKeywords: ['3 minutes', 'incoming batter'],
    applicableFormat: 'ALL',
  },
  {
    id: 'EVAL-03',
    category: 'non_striker_run_out',
    query: 'Can a bowler run out the non-striker backing up before delivery?',
    expectedLaw: 41,
    expectedClause: '41.16',
    expectedOrg: 'MCC',
    expectedKeywords: ['release the ball', 'run out'],
    applicableFormat: 'ALL',
  },
  {
    id: 'EVAL-04',
    category: 'competition_specific_playing_condition',
    query: 'Is there a Free Hit for every No ball in T20 Internationals?',
    expectedLaw: 21,
    expectedClause: '21.19',
    expectedOrg: 'ICC',
    expectedKeywords: ['Free Hit', 'No ball'],
    applicableFormat: 'T20I',
  },
  {
    id: 'EVAL-05',
    category: 'scenario_boundary_catch',
    query: 'A fielder catches the ball after stepping over the boundary. Is it a six or a catch?',
    expectedLaw: 19,
    expectedClause: '19.5.2',
    expectedOrg: 'MCC',
    expectedKeywords: ['grounded beyond the boundary', 'last contact'],
    applicableFormat: 'ALL',
  },
  {
    id: 'EVAL-06',
    category: 'over_rate_penalty',
    query: 'What is the in-match penalty if the fielding team fails to start the 20th over in time in T20I?',
    expectedLaw: null,
    expectedClause: '13.7',
    expectedOrg: 'ICC',
    expectedKeywords: ['one fewer fielder', '30-yard'],
    applicableFormat: 'T20I',
  },
  {
    id: 'EVAL-07',
    category: 'dangerous_bowling',
    query: 'What is the rule on bowling a beamer above waist height?',
    expectedLaw: 41,
    expectedClause: '41.7',
    expectedOrg: 'MCC',
    expectedKeywords: ['waist height', 'No ball'],
    applicableFormat: 'ALL',
  },
  {
    id: 'EVAL-08',
    category: 'unsupported_query',
    query: 'What are the rules regarding VAR offside decisions in soccer?',
    expectedLaw: null,
    expectedClause: null,
    expectedOrg: null,
    expectedKeywords: [],
    shouldAbstain: true,
  },
];
